import React, { useState } from 'react';
import { View, StyleSheet, Pressable, Share, Alert, ScrollView, useWindowDimensions } from 'react-native';
import { Feather } from '@expo/vector-icons';
import { useRoute, RouteProp } from '@react-navigation/native';
import { ThemedText } from '@/components/ThemedText';
import { useTheme } from '@/hooks/useTheme';
import { Spacing, BorderRadius } from '@/constants/theme';
import { withOpacity } from '@/utils/colorUtils';

type PatternStackParamList = {
  PatternViewer: { svg: string; templateName: string };
};

export default function PatternViewerScreen() {
  const { theme } = useTheme();
  const route = useRoute<RouteProp<PatternStackParamList, 'PatternViewer'>>();
  const { svg, templateName } = route.params;
  const { width: screenWidth } = useWindowDimensions();
  const [zoom, setZoom] = useState(1);

  const handleShare = async () => {
    try {
      await Share.share({
        message: `${templateName} Pattern - Generated by TailorFlow\n\nPattern has been generated successfully. Print at actual size for best results.`,
        title: `${templateName} Pattern`,
      });
    } catch (error) {
      Alert.alert('Error', 'Failed to share pattern');
    }
  };

  const handlePrint = () => {
    Alert.alert(
      'Print Pattern',
      'To print this pattern:\n\n1. Take a screenshot\n2. Transfer to computer\n3. Print at actual size (scale 1:10)\n\nFor best results, ensure your printer is set to "Actual Size" or "100%".',
      [{ text: 'OK' }]
    );
  };

  const handleZoomIn = () => {
    setZoom(prev => Math.min(prev + 0.25, 3));
  };

  const handleZoomOut = () => {
    setZoom(prev => Math.max(prev - 0.25, 0.5));
  };

  return (
    <View style={[styles.container, { backgroundColor: theme.backgroundRoot }]}>
      <View style={[styles.toolbar, { borderBottomColor: theme.borderLight }]}>
        <View style={styles.zoomControls}>
          <Pressable style={[styles.toolButton, { backgroundColor: theme.backgroundDefault }]} onPress={handleZoomOut}>
            <Feather name="zoom-out" size={20} color={theme.text} />
          </Pressable>
          <ThemedText style={styles.zoomText}>{Math.round(zoom * 100)}%</ThemedText>
          <Pressable style={[styles.toolButton, { backgroundColor: theme.backgroundDefault }]} onPress={handleZoomIn}>
            <Feather name="zoom-in" size={20} color={theme.text} />
          </Pressable>
        </View>
        <View style={styles.actionButtons}>
          <Pressable
            style={[styles.actionButton, { backgroundColor: withOpacity(theme.primary, 0.12) }]}
            onPress={handleShare}
          >
            <Feather name="share-2" size={18} color={theme.primary} />
            <ThemedText type="small" style={{ color: theme.primary, marginLeft: Spacing.xs }}>
              Share
            </ThemedText>
          </Pressable>
          <Pressable
            style={[styles.actionButton, { backgroundColor: withOpacity(theme.success, 0.12) }]}
            onPress={handlePrint}
          >
            <Feather name="printer" size={18} color={theme.success} />
            <ThemedText type="small" style={{ color: theme.success, marginLeft: Spacing.xs }}>
              Print
            </ThemedText>
          </Pressable>
        </View>
      </View>

      <ScrollView 
        style={styles.scrollContainer}
        contentContainerStyle={styles.scrollContent}
        horizontal
        showsHorizontalScrollIndicator={false}
      >
        <ScrollView 
          nestedScrollEnabled
          showsVerticalScrollIndicator={false}
          contentContainerStyle={{ alignItems: 'center', padding: Spacing.lg }}
        >
          <View 
            style={[
              styles.patternContainer, 
              { 
                backgroundColor: theme.backgroundDefault,
                transform: [{ scale: zoom }],
                width: screenWidth - Spacing.lg * 2,
              }
            ]}
          >
            <ThemedText type="bodyMedium" style={styles.patternTitle}>
              {templateName} Pattern
            </ThemedText>
            <View style={styles.svgPlaceholder}>
              <Feather name="layout" size={48} color={theme.textSecondary} />
              <ThemedText type="small" style={{ color: theme.textSecondary, marginTop: Spacing.md, textAlign: 'center' }}>
                Pattern preview generated{'\n'}(SVG rendering requires react-native-svg)
              </ThemedText>
              <ThemedText type="caption" style={{ color: theme.textSecondary, marginTop: Spacing.sm }}>
                The pattern includes:
              </ThemedText>
              <View style={styles.piecesList}>
                <ThemedText type="small" style={{ color: theme.text }}>Front Bodice (Cut 1 on fold)</ThemedText>
                <ThemedText type="small" style={{ color: theme.text }}>Back Bodice (Cut 1 on fold)</ThemedText>
                <ThemedText type="small" style={{ color: theme.text }}>Sleeve (Cut 2)</ThemedText>
              </View>
            </View>
            <ThemedText type="caption" style={[styles.footer, { color: theme.textSecondary }]}>
              Generated by TailorFlow - Scale 1:10
            </ThemedText>
          </View>
        </ScrollView>
      </ScrollView>

      <View style={[styles.infoCard, { backgroundColor: theme.backgroundDefault }]}>
        <View style={styles.infoRow}>
          <Feather name="info" size={16} color={theme.textSecondary} />
          <ThemedText type="small" style={{ color: theme.textSecondary, marginLeft: Spacing.sm, flex: 1 }}>
            Pattern pieces include seam allowance. All measurements are in inches.
          </ThemedText>
        </View>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  toolbar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: Spacing.md,
    borderBottomWidth: 1,
  },
  zoomControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  toolButton: {
    width: 36,
    height: 36,
    borderRadius: BorderRadius.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  zoomText: {
    width: 50,
    textAlign: 'center',
  },
  actionButtons: {
    flexDirection: 'row',
    gap: Spacing.sm,
  },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.sm,
  },
  scrollContainer: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
  },
  patternContainer: {
    padding: Spacing.lg,
    borderRadius: BorderRadius.lg,
    alignItems: 'center',
  },
  patternTitle: {
    marginBottom: Spacing.lg,
  },
  svgPlaceholder: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: Spacing.xl,
    minHeight: 300,
  },
  piecesList: {
    marginTop: Spacing.md,
    gap: Spacing.xs,
  },
  footer: {
    marginTop: Spacing.lg,
    textAlign: 'center',
  },
  infoCard: {
    margin: Spacing.md,
    padding: Spacing.md,
    borderRadius: BorderRadius.md,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
});
